name: Expo

on:
  pull_request:
    branches: [main]

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: npm install

      - name: Make sure Expo can successfully export
        run: npx expo export
